server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/enterprise-dev-search-database
    username: enterprise
    password: "D1g1Commerce"
  jpa:
    show-sql: true

platform:
  initialdata:
    core:
      auto-import: true
    sample:
      auto-import: true

search:
  product:
    config-name: ENTERPRISE_DEV_PRODUCTS
    index-endpoint: http://localhost:8080/ep/index/products
