server:
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://172.16.16.110:3306/digi_ep_ws_demo_dev
    username: digi
    password: "Digi@123"
  jpa:
    show-sql: true

platform:
  initialdata:
    core:
      auto-import: true
    sample:
      auto-import: true

search:
  product:
    config-name: ENTERPRISE_PRODUCTS
    index-endpoint: http://172.16.16.117:8080/ep/index/products
