server:
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digi_ep_ws_demo_dev
    username: root
    password: root
  jpa:
    show-sql: true

platform:
  initialdata:
    core:
      auto-import: true
    sample:
      auto-import: true

search:
  product:
    config-name: ENTERPRISE_PRODUCTS
    index-endpoint: http://localhost:8088/index/products

