server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/b2b_platform
    username: root
    password: root
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    url: /api-docs.yaml

platform:
  initialdata:
    core:
      auto-import: true
    sample:
      auto-import: true


